name: "Release from tag"

on:
  push:
    tags:
      - "v*"

jobs:
  gh_tagged_release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'


    - uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r21e
        add-to-path: false

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build all with Gradle
      run: ./gradlew assembleRelease
      env:
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

    - name: Publish library (.aar) to Maven Central
      run: ./gradlew "-PsigningInMemoryKey=${{ secrets.ARTIFACT_SIGNING_KEY }}" "-PsigningInMemoryKeyPassword=${{ secrets.ARTIFACT_SIGNING_PASSWORD }}" "-PmavenCentralUsername=${{ secrets.MAVEN_CENTRAL_USERNAME }}" "-PmavenCentralPassword=${{ secrets.MAVEN_CENTRAL_PASSWORD }}" :library:publish --stacktrace
      env:
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

    - uses: r0adkll/sign-android-release@v1
      name: Sign app APK
      # ID used to access action output
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.APPLICATION_SIGNING_KEY_STORE }}
        keyStorePassword: ${{ secrets.APPLICATION_SIGNING_KEY_STORE_PASSWORD }}
        alias: ${{ secrets.APPLICATION_SIGNING_KEY_STORE_ALIAS }}
        keyPassword: ${{ secrets.APPLICATION_SIGNING_KEY_STORE_ALIAS_PASSWORD }}

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          LICENSE
          library/build/outputs/aar/*.aar
          app/build/outputs/apk/release/*-signed.apk
      id: "automatic_releases"
